- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/GUI.h
I've attempted to retain old configs by checking for it in the Config constructor, so hopefully no one losses theirs. I haven't done any work in C++ before, so hopefully this is all up to standard. Added some custom ImGui controls so I could get the window looking how I wanted it to (the hardcoded text paddings need to be set to the corresponding style variable).
> Add multiple config support

- README.md
When you change LICENSE in GitHub, this badge will auto update.
> Auto choose license from GitHub

- Osiris/Hacks/Backtrack.cpp
- Osiris/Hacks/Chams.cpp
- README.md
also fix ignoresmoke and backtrack chams to work with health based option enabled
> add backtrack into readme

- Osiris/GUI.cpp
Indicates when keybind change is triggered
> Gui enhancement

- Osiris/SDK/Entity.h
I've updated offsets tonight (https://github.com/danielkrupinski/Osiris/issues/542#issuecomment-533390664) and carefully tested - all works correctly. Please merge this pull request, as i am original author of code.
> Updated offsets

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Misc.cpp
- Osiris/Hacks/Misc.h
- Osiris/Hooks.cpp
- Osiris/SDK/Entity.h
added grenade prediction and updated vtable indexes (referenced in issue [452](https://github.com/danielkrupinski/Osiris/issues/542)) due to new update.
> Added Grenade Prediction

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Esp.cpp
just a simple corner esp for those who like that better than box-esp.
Color is configured with box-esp color
preview:
https://i.imgur.com/hn4zFpj.png
> corner esp

- Osiris/SDK/Entity.h
Fresh update, fresh crash, fresh fix. Have a nice day.
> Updated virtual method indices

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Esp.cpp
Hello Daniel,
Thank you for adding WeaponData!!!
I added activeWeapon to Player ESP. I find it usefull.
Maybe you take a look please?
The Positioning is not final, because I have to test it out. But you know better than me where it can be positioned.
Thank you very much!
best regards
> Adding activeWeapon to Player ESP with Config

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Misc.cpp
- Osiris/Hacks/Misc.h
- Osiris/Hooks.cpp
This is my way of removing panorama blur
example: https://www.youtube.com/watch?v=QD1n97i4TEU
> Remove Blur in HUD (Panorama Blur)

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Visuals.cpp
- Osiris/Hacks/Visuals.h
- Osiris/Hooks.cpp
> Player Model

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Misc.cpp
- Osiris/Hacks/Misc.h
- Osiris/Hooks.cpp
as title says^^
ive been using it for a good while now so i thought it was time to give it away without bugs :)
> Aspect ratio changer (stretch changer)

- Osiris/Hacks/Misc.h
I believe some values for the autostrafe were not right, and i feel this change fixes autostrafe cause it was kind of wonky before
> Autostrafe fix?

- Osiris/Netvars.cpp
> Make deagle spinner spin only on inspect

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Esp.cpp
- Osiris/Hacks/Visuals.cpp
- Osiris/Hacks/Visuals.h
- Osiris/Hooks.cpp
I could make it so that it fades out, but I'm too lazy right now.
Donated btw. I forgot to add my name to the message. ;)
> Default Hitmarker

- Osiris/GUI.cpp
- Osiris/Hacks/Chams.cpp
- Osiris/Hacks/Chams.h
- Osiris/SDK/Material.h
> Glow Material For Chams

- README.md
adds the glow material on chams
> very small readme update

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/GUI.cpp
- Osiris/Hacks/Esp.cpp
- Osiris/SDK/Entity.h
Re opened for a third time because i am an idiot, but this one works and the commits aren't fucked up anymore.
Did it from an alt account so i can have seperate PRs
Preview:
> Added Ammo to Weapon ESP [AGAIN]

- Osiris/Hacks/Aimbot.cpp
Blocks accidental team damage while AimBOT's friendly fire setting is turned off and visible only too.
> AimBOT's AutoWall Team Check Fix

- Osiris/SDK/Entity.h
> Fixing AnimState offset for latest patch

- Osiris/GUI.cpp
- Osiris/Hacks/Chams.cpp
- Osiris/Hacks/Chams.h
by [sapphire](https://github.com/Sapphire1337420)
and [Mustafa](https://github.com/MustafaDaPro)
> Added Metallic and Pearlescent chams

- Osiris/SDK/WeaponId.h
- Osiris/nSkinz/item_definitions.cpp
- Osiris/nSkinz/item_definitions.hpp
#2375
[Preview](https://cdn.discordapp.com/attachments/673647351331815431/785150568674623508/Screenshot_257.png)
> Added Brokenfang gloves

- Osiris/Memory.cpp
Improves Memory class initialization performance by ~35%
> Implement Boyer-Moore algorithm for memory pattern searching

- Osiris/GUI.cpp
- Osiris/Hacks/SkinChanger.cpp
- Osiris/Hacks/SkinChanger.h
- Osiris/Hooks.cpp
- Osiris/Interfaces.h
- Osiris/Osiris.vcxproj
- Osiris/Osiris.vcxproj.filters
- Osiris/SDK/FileSystem.h
- Osiris/SDK/ItemSchema.h
- Osiris/SDK/Platform.h
- Osiris/imgui/imgui_impl_dx9.cpp
- Osiris/stb_image.h
> Skin Preview

- Osiris/Config.cpp
- Osiris/Config.h
- Osiris/EventListener.cpp
- Osiris/GUI.cpp
- Osiris/Hacks/Misc.cpp
- Osiris/Hacks/Misc.h
didn't test this so tell me if there are any problems
it outputs to console right now and it's just fine, but is there a way to output messages to chat and only have local player see them?
> Add vote revealer

- Osiris/Config.cpp
> Allow Json Comments

- Osiris/Hacks/Misc.cpp
See no reason for it to be disabled on Linux
> Allow Fake Prime on Linux

- Osiris/Hacks/InventoryChanger.cpp
(Still can't open these cases with keys added by inventory changer.)
> Add cases to inventory changer.

- Osiris/SDK/GameUI.h
> Fix GameUI::createCommandMsgBox() index

- Osiris/Memory.cpp
OMG, spend almost whole day on this crap but i'll not let linux version of Osiris to die.
> Update Memory::lineGoesThroughSmoke pattern for Linux

- Osiris/SDK/Entity.h
Fix Quick Reload for Linux (#3391)
> Fixed Entity->isInReload() for Linux

- Source/InventoryChanger/InventoryChanger.cpp
unfixed: https://i.imgur.com/3Q72r9Y.mp4
fixed: https://i.imgur.com/FrrYxVg.mp4
> Fixed sequence for falchion knife

- Source/CS2/Constants/PanelIDs.h
- Source/Endpoints.h
- Source/FeatureHelpers/PlayedSounds.h
- Source/Features/Features.h
- Source/Features/Sound/FootstepVisualizer.h
- Source/Features/Sound/SoundFeatures.h
- Source/GlobalContext.h
- Source/Intrinsics.cpp
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Footstep visualization

- Source/CS2/Constants/SoundNames.h
- Source/FeatureHelpers/FeatureHelpers.h
- Source/FeatureHelpers/Sound/BombBeepSound.h
- Source/FeatureHelpers/Sound/BombBeepVisualizerHelpers.h
- Source/FeatureHelpers/Sound/SoundWatcher.h
- Source/Features/Sound/BombBeepVisualizer.h
- Source/Features/Sound/SoundFeatures.h
- Source/GlobalContext.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Bomb beep sound visualization

- Source/CS2/Constants/SoundNames.h
- Source/FeatureHelpers/HudInWorldPanelZOrder.h
- Source/FeatureHelpers/Sound/SoundWatcher.h
- Source/FeatureHelpers/Sound/WeaponScopeSound.h
- Source/Features/Sound/SoundFeatures.h
- Source/Features/Sound/WeaponScopeVisualizer.h
- Source/Intrinsics.cpp
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Weapon scope sound visualization

- Source/CS2/Classes/Panorama.h
- Source/FeatureHelpers/PanelShadowParams.h
- Source/FeatureHelpers/PanelStylePropertyFactory.h
- Source/FeatureHelpers/PanelStyleSetter.h
- Source/FeatureHelpers/PanoramaLabelFactory.h
- Source/FeatureHelpers/RenderingHookEntityLoop.h
- Source/FeatureHelpers/StylePropertiesSymbols.h
- Source/FeatureHelpers/StylePropertiesVMTs.h
- Source/Features/Sound/Details/SoundVisualizationPanelFactory.h
- Source/Features/Visuals/PlayerInformationThroughWalls.h
- Source/Features/Visuals/States/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/States/VisualFeaturesStates.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/Implementation/PanoramaLabelImpl.h
- Source/GlobalContext/FullGlobalContext.h
- Source/HookDependencies/HookDependencies.h
- Source/HookDependencies/HookDependenciesMask.h
- Source/MemoryPatterns/Linux/PanoramaLabelPatternsLinux.h
- Source/MemoryPatterns/PanoramaLabelPatterns.h
- Source/MemoryPatterns/Windows/PanoramaLabelPatternsWindows.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement showing players' health through walls

- Source/Features/Visuals/PlayerInformationThroughWalls.h
- Source/Features/Visuals/States/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/VisualFeatures.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
- Source/Utils/ColorUtils.h
- Source/Utils/InRange.h
> Implement player health text color based on health value

- Source/CS2/Classes/Entities/CCSPlayerController.h
- Source/CS2/Constants/ColorConstants.h
- Source/Features/Visuals/PlayerInformationThroughWalls.h
- Source/Features/Visuals/States/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/Implementation/PlayerControllerImpl.h
- Source/GameClasses/OffsetTypes/PlayerControllerOffset.h
- Source/MemoryPatterns/Linux/PlayerControllerPatternsLinux.h
- Source/MemoryPatterns/PlayerControllerPatterns.h
- Source/MemoryPatterns/Windows/PlayerControllerPatternsWindows.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement player position arrow color based on player color

- Source/CS2/Classes/Entities/C_CSPlayerPawn.h
- Source/CS2/Constants/ColorConstants.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationPanel.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWalls.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsPanelFactory.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerStateIcons/PlayerStateIconsToShow.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/Implementation/PlayerPawnImpl.h
- Source/GameClasses/OffsetTypes/PlayerPawnOffset.h
- Source/MemoryPatterns/Linux/PlayerPawnPatternsLinux.h
- Source/MemoryPatterns/PlayerPawnPatterns.h
- Source/MemoryPatterns/Windows/PlayerPawnPatternsWindows.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement showing an icon on player defusing the bomb

- Source/CS2/Classes/Entities/C_CSPlayerPawn.h
- Source/CS2/Constants/ColorConstants.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWalls.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsPanelFactory.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerStateIcons/PlayerStateIconsToShow.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/Implementation/PlayerPawnImpl.h
- Source/GameClasses/OffsetTypes/PlayerPawnOffset.h
- Source/MemoryPatterns/Linux/PlayerPawnPatternsLinux.h
- Source/MemoryPatterns/PlayerPawnPatterns.h
- Source/MemoryPatterns/Windows/PlayerPawnPatternsWindows.h
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement showing an icon on player picking up a hostage

- Source/CS2/Classes/Entities/C_CSWeaponBase.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationPanel.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWalls.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsPanelFactory.h
- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWallsState.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/Implementation/GameClassImplementations.h
- Source/GameClasses/Implementation/WeaponImpl.h
- Source/GameClasses/OffsetTypes/WeaponOffset.h
- Source/MemoryPatterns/Linux/LinuxPatterns.h
- Source/MemoryPatterns/Linux/WeaponPatternsLinux.h
- Source/MemoryPatterns/MemoryPatterns.h
- Source/MemoryPatterns/Windows/WeaponPatternsWindows.h
- Source/MemoryPatterns/Windows/WindowsPatterns.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement showing players' active weapon ammo

- Source/Features/Visuals/PlayerInformationThroughWalls/PlayerInformationThroughWalls.h
- Source/Features/Visuals/PlayerOutlineGlow/PlayerOutlineGlow.h
- Source/Features/Visuals/PlayerOutlineGlow/PlayerOutlineGlowColorType.h
- Source/Features/Visuals/PlayerOutlineGlow/PlayerOutlineGlowToggle.h
- Source/GameClasses/PlayerPawn.h
- Source/UI/Panorama/CreateGUI.js
> Implement player outline glow color based on player health

- Source/CS2/Classes/Entities/CBaseAnimGraph.h
- Source/Features/Visuals/OutlineGlow/DefuseKitOutlineGlow/DefuseKitOutlineGlow.h
- Source/Features/Visuals/OutlineGlow/DefuseKitOutlineGlow/DefuseKitOutlineGlowContext.h
- Source/Features/Visuals/OutlineGlow/DefuseKitOutlineGlow/DefuseKitOutlineGlowParams.h
- Source/Features/Visuals/OutlineGlow/DefuseKitOutlineGlow/DefuseKitOutlineGlowState.h
- Source/Features/Visuals/OutlineGlow/DefuseKitOutlineGlow/DefuseKitOutlineGlowToggle.h
- Source/Features/Visuals/OutlineGlow/OutlineGlow.h
- Source/Features/Visuals/OutlineGlow/OutlineGlowContext.h
- Source/Features/Visuals/VisualFeatures.h
- Source/Features/Visuals/VisualFeaturesStates.h
- Source/GameClasses/BaseEntity.h
- Source/GameDependencies/EntitiesVMTs.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement outline glow for defuse kits on ground nearby

- Source/CS2/Classes/CPlantedC4.h
- Source/CS2/Constants/EntityTypeNames.h
- Source/Features/Hud/BombTimer/BombTimerContext.h
- Source/Features/Visuals/OutlineGlow/OutlineGlow.h
- Source/Features/Visuals/OutlineGlow/OutlineGlowContext.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlow.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlowCondition.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlowContext.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlowParams.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlowState.h
- Source/Features/Visuals/OutlineGlow/TickingBombOutlineGlow/TickingBombOutlineGlowToggle.h
- Source/Features/Visuals/VisualFeatures.h
- Source/Features/Visuals/VisualFeaturesStates.h
- Source/GameClasses/PlantedC4.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement outline glow for ticking bomb

- Source/Features/Visuals/PlayerInfoInWorld/PlayerInfoInWorld.h
- Source/Features/Visuals/PlayerInfoInWorld/PlayerInfoInWorldPanelFactory.h
- Source/Features/Visuals/PlayerInfoInWorld/PlayerStateIcons/PlayerStateIconsPanel.h
- Source/Features/Visuals/PlayerInfoInWorld/PlayerStateIcons/PlayerStateIconsPanelParams.h
- Source/Features/Visuals/PlayerInfoInWorld/PlayerStateIcons/PlayerStateIconsToShow.h
- Source/Features/Visuals/VisualFeatures.h
- Source/GameClasses/BaseEntity.h
- Source/GameClasses/C4.h
- Source/GameClasses/PlayerPawn.h
- Source/GameClasses/PlayerWeapons.h
- Source/GameClasses/WeaponServices.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement bomb carrier icon in "Player Info in World"

- Source/CS2/Constants/ColorConstants.h
- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/GameClasses/PlayerController.h
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement player model glow color based on player color

- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/GameClasses/PlayerPawn.h
- Source/UI/Panorama/CreateGUI.js
> Implement player model glow color based on player health

- Source/CS2/Classes/Entities/C_CSWeaponBase.h
- Source/Endpoints.h
- Source/Entities/BaseEntity.h
- Source/Entities/BaseWeapon.h
- Source/FeatureHelpers/EntityClassifier.h
- Source/FeatureHelpers/RenderingHookEntityLoop.h
- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/Features/Visuals/ModelGlow/PlayerModelGlow/PlayerModelGlow.h
- Source/Features/Visuals/ModelGlow/WeaponModelGlow/WeaponModelGlow.h
- Source/Features/Visuals/ModelGlow/WeaponModelGlow/WeaponModelGlowParams.h
- Source/GlobalContext/GlobalContext.h
- Source/LinuxEndpoints.s
- Source/MemoryPatterns/Linux/WeaponPatternsLinux.h
- Source/MemoryPatterns/PatternTypes/WeaponPatternTypes.h
- Source/MemoryPatterns/Windows/WeaponPatternsWindows.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
- Source/WindowsEndpoints.asm
> Implement weapon model glow feature

- Source/Entities/BaseWeapon.h
- Source/Entities/C4.h
- Source/Features/Visuals/ModelGlow/DroppedBombModelGlow/DroppedBombModelGlow.h
- Source/Features/Visuals/ModelGlow/DroppedBombModelGlow/DroppedBombModelGlowParams.h
- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement dropped bomb model glow feature

- Source/Entities/BaseEntity.h
- Source/Entities/PlantedC4.h
- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/Features/Visuals/ModelGlow/TickingBombModelGlow/TickingBombModelGlow.h
- Source/Features/Visuals/ModelGlow/TickingBombModelGlow/TickingBombModelGlowParams.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement ticking bomb model glow feature

- Source/Entities/BaseEntity.h
- Source/Features/Visuals/ModelGlow/DefuseKitModelGlow/DefuseKitModelGlow.h
- Source/Features/Visuals/ModelGlow/DefuseKitModelGlow/DefuseKitModelGlowParams.h
- Source/Features/Visuals/ModelGlow/ModelGlow.h
- Source/Features/Visuals/ModelGlow/ModelGlowState.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/SetCommandHandler.h
> Implement defuse kit model glow feature

- Source/Config/Config.h
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/PanoramaCommandDispatcher.h
> Add an option to restore default settings in the active config

- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/PanoramaGUI.h
> Move model glow preview to the left side of the model glow tab

- Source/Features/Visuals/ModelGlow/ModelGlowConfigVariables.h
- Source/Features/Visuals/ModelGlow/ModelGlowParams.h
- Source/Features/Visuals/ModelGlow/ModelGlowToggle.h
- Source/Features/Visuals/ModelGlow/PlayerModelGlow/PlayerModelGlow.h
- Source/Features/Visuals/ModelGlow/Preview/EnemyTeam.h
- Source/Features/Visuals/ModelGlow/Preview/PlayerModelGlowPreview.h
- Source/Features/Visuals/ModelGlow/Preview/PlayerModelGlowPreviewColorMode.h
- Source/Features/Visuals/ModelGlow/Preview/PlayerModelGlowPreviewParams.h
- Source/Features/Visuals/ModelGlow/Preview/PlayerModelGlowPreviewState.h
- Source/Features/Visuals/ModelGlow/Preview/PlayerPawnForModelGlowPreview.h
- Source/Osiris.vcxproj
- Source/Osiris.vcxproj.filters
- Source/UI/Panorama/CreateGUI.js
- Source/UI/Panorama/PanoramaGUI.h
- Source/Utils/ColorUtils.h
- Source/Utils/InRange.h
> Implement "Enemy / Ally" color mode for player model glow
